---
# tasks file for vector

- name: Vector | Create directory 
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root         
  with_items:
    - "{{ vector_path }}"
    - "{{ vector_config }}"
  tags:
    - vector
- name: Vector | download Vector
  become: true
  get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    dest: "{{ vector_path }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    mode: 755
  tags:
    - vector
- name: Vector | Unarchive files
  become: true
  unarchive:
    src: "{{ vector_path }}/vector-{{ vector_version }}-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
    dest: "{{ vector_path }}"
    remote_src: true
    creates: "{{ vector_path }}/bin"
    extra_opts: [--strip-components=2]
  tags:
    - vector
- name: Vector | Create service
  become: true
  template:
    src: ./templates/vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: root
    group: root
  tags:
    - vector
- name: Vector | Creat config
  become: true
  ansible.builtin.template:
    src: ./templates/vector.toml.j2
    dest: "{{ vector_config }}/vector.toml"
    owner: root
    group: root
    mode: '0755'
    force: true
  tags:
    - vector
- name: Vector | Start vector
  become: true
  systemd:
    name: vector
    state: "started"
    enabled: true
    daemon_reload: true
  tags:
    - vector
