---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos_8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    privileged: true
  - name: ubuntu_latest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    privileged: true
  # - name: instance
  #   image: quay.io/centos/centos:stream8
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
